In [2]:
import modern_robotics as mr 
import numpy as np

# Notebook for converting vectors back and forth from vector and matrix enterpritations. 

## Converting 3-vector (such as angular velocities) to their 3-matrix representation

In [3]:


mr.VecToso3([0, 0, 1])

array([[ 0, -1,  0],
       [ 1,  0,  0],
       [ 0,  0,  0]])

## Converting 3-matrix (such as matrix representations of angular velocities) to their 3-vector representation

In [4]:

mr.so3ToVec([[0, -1, 0], 
             [1, 0, 0],
             [0, 0, 0]])

array([0, 0, 1])

## Converting a 6-vector (such as screw axis) to its 4-matrix representation

In [9]:
mr.VecTose3([0, 0, 0, 0, 1, 0])

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Converting a 4-matrix (such as a screw axis matrix) to its 6-vector representation

In [7]:
mr.se3ToVec([[0, -1, 0, 0],
            [1, 0, 0, 0], 
            [0, 0, 0, 0], 
            [0, 0, 0, 0]])

array([0, 0, 1, 0, 0, 0])

## Taking exponential of 3-matrix

In [12]:
mr.MatrixExp3([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]]).round(2)

array([[1.67, 0.81, 0.94],
       [1.48, 2.82, 2.15],
       [2.29, 2.82, 4.36]])

## Taking exponential of 6-matrix

In [14]:
mr.MatrixExp6([[0, -1, 0, 0], 
               [1, 0, 0, 0], 
               [0, 0, 0, 0], 
               [0, 0, 0, 0]]).round(2)

array([[ 0.54, -0.84,  0.  ,  0.  ],
       [ 0.84,  0.54,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

## Doing forward kinematics in space and body
Returns the transformation between the space frame and body frame given the angle displacement of each joint. 

- M : relation between space frame and body frame, 4x4
- S : List of screw axis of each joint, 6x1 * number of joints 
- theta : List of angles each joint move, 1x number of joints

In [69]:

M = [[-1, 0, 0, 0], 
     [0, 0, 1, 3], 
     [0, 1, 0, 2], 
     [0, 0, 0, 1]]
S = np.array([[0, 1, 0, 3, 0, 0], [-1, 0, 0, 0, 3, 0], [0, 0, 0, 0, 0, 1]]).T
theta = [np.pi/2, np.pi/2, 1]

#mr.FKinSpace(M, S, theta).round(2)

mr.FKinBody(M, S, theta).round(2)





array([[-0.,  1., -0., -0.],
       [-1., -0.,  0.,  0.],
       [ 0.,  0.,  1.,  6.],
       [ 0.,  0.,  0.,  1.]])

### Giving coords to each joint in a forwards kinematics problem
Running this loop gives transformations for each joint in a forward kinematics problem. 

NOTE! Use this code along with exercise to double check that everything makes sense. 


In [64]:
hyper_M = [
    [[1, 0, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 1, 2],
     [0, 0, 0, 1]],

    [[1, 0, 0, 0], 
     [0, 1, 0, 3],
     [0, 0, 1, 2], 
     [0, 0, 0, 1]],

    [[-1, 0, 0, 0], 
     [0, 0, 1, 3], 
     [0, 1, 0, 2], 
     [0, 0, 0, 1]]]
S = np.array([[0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 2, 0], [0, 0, 0, 0, 1, 0]])

theta = [np.pi/2, np.pi/2, 1]

for i, M in enumerate(hyper_M): 

    if i+1 == len(hyper_M): 

        print(f"Transformation of body frame:    \n", mr.FKinSpace(M=M, Slist=S[:i+1].T, thetalist=theta[:i+1]).round(2) )

    else: 
        print(f"Transformation of joint {i+2}:    \n", mr.FKinSpace(M=M, Slist=S[:i+1].T, thetalist=theta[:i+1]).round(2) )


Transformation of joint 2:    
 [[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  1.]]
Transformation of joint 3:    
 [[ 0. -0.  1. -0.]
 [ 1.  0. -0.  0.]
 [ 0.  1.  0.  5.]
 [ 0.  0.  0.  1.]]
Transformation of body frame:    
 [[-0.  1. -0. -0.]
 [-1. -0.  0.  0.]
 [ 0.  0.  1.  6.]
 [ 0.  0.  0.  1.]]


## Calculating the Space/ body jacobian given screw axes and joint angles

In [6]:

S_list = np.array([[0, 1, 0, 3, 0, 0], [-1, 0, 0, 0, 3, 0], [0, 0, 0, 0, 0, 1]]).T

theta = [np.pi/2, np.pi/2, 1]

mr.JacobianSpace(Slist=S_list, thetalist=theta).round(2)

mr.JacobianBody(Blist=S_list, thetalist=theta).round(2)


array([[ 0., -1.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  1.]])